Use a statefulset for oauth2-proxy redis sentinel cluster
By using a script that checks the pod ordinal, different arguments can be passed to redis-server depending on if pod should default to primary behavior or secondary behavior
This way, there's no need to have two separate pod definitions, and scaling is thus easier.

diff --git a/apps/oauth2-proxy/configmaps.yaml b/apps/oauth2-proxy/configmaps.yaml
--- a/apps/oauth2-proxy/configmaps.yaml
+++ b/apps/oauth2-proxy/configmaps.yaml
@@ -3,12 +3,34 @@ kind: ConfigMap
 metadata:
   name: redis-scripts
 data:
-  redis-primary.sh: redis-server /configs/redis.conf --cluster-announce-ip $POD_IP --cluster-announce-port 26379
+  # start redis or sentinel as primary or secondary depending on ordinal
+  # ordinal 0 is primary by default, further pods are secondary by default
+  # sentinels handle primary election if ordinal 0 ever fails or restarts and cleanly promotes another replica to primary, and demotes ordinal 0 when it comes back up
+  # of note: new secondary nodes require ordinal 0 to be healthy in order to do initial sync. scaling might fail if ordinal 0 is unhealthy.
+  startup.sh: |
+    #!/bin/sh
+    ORDINAL=${HOSTNAME##*-}
+    if [ "$1" = "redis" ] && [ $ORDINAL = "0" ]
+    then
+      # redis primary
+      redis-server /configs/redis.conf --cluster-announce-ip $POD_IP --cluster-announce-port 26379
+    elif [ "$1" = "redis" ] && [ $ORDINAL != "0" ]
+    then
+      # redis secondary
+      redis-server /configs/redis.conf --replica-announce-ip $POD_IP --replicaof oauth2-redis-0.oauth2-redis.default.svc.cluster.local 6379
+    elif [ "$1" = "sentinel" ] && [ $ORDINAL = "0" ]
+    then
+      # sentinel primary
+      redis-server /configs/sentinel.conf --sentinel announce-ip $POD_IP --sentinel monitor oauth2 $POD_IP 6379 2
+    elif [ "$1" = "sentinel" ] && [ $ORDINAL != "0" ]
+    then
+      # sentinel secondary
+      redis-server /configs/sentinel.conf --sentinel announce-ip $POD_IP --sentinel monitor oauth2 oauth2-redis-0.oauth2-redis.default.svc.cluster.local 6379 2
+    else
+      exit 1
+    fi
   # sentinel monitor syntax: --sentinel monitor PRIMARY_NAME PRIMARY_HOST_NAME_OR_IP REDIS_PORT QUORUM
   # QUORUM is the number of sentinels that need to agree that the primary is down in order to promote a secondary
-  sentinel-primary.sh: redis-server /configs/sentinel.conf --sentinel announce-ip $POD_IP --sentinel monitor oauth2-proxy $POD_IP 6379 2
-  redis-secondary.sh: redis-server /configs/redis.conf --replica-announce-ip $POD_IP --replicaof oauth2-proxy-redis-primary 6379
-  sentinel-secondary.sh: redis-server /configs/sentinel.conf --sentinel announce-ip $POD_IP --sentinel monitor oauth2-proxy oauth2-proxy-redis-primary 6379 2
 ---
 apiVersion: v1
 kind: ConfigMap
@@ -26,7 +48,7 @@ data:
     port 26379
     protected-mode no
     sentinel announce-port 26379
-    sentinel down-after-milliseconds oauth2-proxy 5000
-    sentinel parallel-syncs oauth2-proxy 1
-    sentinel failover-timeout oauth2-proxy 180000
+    sentinel down-after-milliseconds oauth2 5000
+    sentinel parallel-syncs oauth2 1
+    sentinel failover-timeout oauth2 180000
     sentinel resolve-hostnames yes
